### PR TITLE
Add Marvin to the README

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
Marvin is our newest project maintainer, this PR adds his name to the conda-forge feedstock README page.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Genevieve! 😄

If we add him to this list (see below) and re-render (asking the bot will do that), that should take care of all the other things in the feedstock that need to be updated

https://github.com/conda-forge/dask-image-feedstock/blob/35c450911c825a5b705d8fbe2fa7f7ecc768a84f/recipe/meta.yaml#L54-L57

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender

**Comment by GenevieveBuckley** [comment]
@jakirkham I can't figure out where in the settings to invite @m-albert to the dask-image team on conda-forge. Do you remember this from last time? (Not much point adding his name to the files here if he can't merge anything)

**Comment by jakirkham** [comment]
We might want to bump the build number as well given the requirement change. Though think we should be good after that change. Thanks again for handling this Genevieve! 😄

**Comment by jakirkham** [comment]
> @jakirkham I can't figure out where in the settings to invite @m-albert to the dask-image team on conda-forge. Do you remember this from last time? (Not much point adding his name to the files here if he can't merge anything)

Yeah when we merge this PR the bot will add anyone in that recipe list to the team maintaining this feedstock

**Comment by GenevieveBuckley** [comment]
> > @jakirkham I can't figure out where in the settings to invite @m-albert to the dask-image team on conda-forge. Do you remember this from last time? (Not much point adding his name to the files here if he can't merge anything)
> 
> Yeah when we merge this PR the bot will add anyone in that recipe list to the team maintaining this feedstock

Oooooh, ok then!

This process is very opaque and confusing to me. Glad we're getting there slowly.

**Comment by GenevieveBuckley** [comment]
:tada:

**Comment by jakirkham** [comment]
> > Yeah when we merge this PR the bot will add anyone in that recipe list to the team maintaining this feedstock
> 
> Oooooh, ok then!
> 
> This process is very opaque and confusing to me. Glad we're getting there slowly.

Yeah any advice on how we can make this clearer would be welcome.

FWIW we have [this on the webpage]( https://conda-forge.org/#update_recipe ) and [a doc section here]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list ).

**Comment by jakirkham** [comment]
Should add details about the invite are included in this comment ( https://github.com/conda-forge/dask-image-feedstock/commit/9b63e518ac706c6ba00f502786f682c25e2ea640#commitcomment-47718198 )

**Comment by jakirkham** [comment]
Probably the confusion is on me for not pointing out those resources earlier

**Comment by GenevieveBuckley** [comment]
I think I found [those docs](https://conda-forge.org/docs/maintainer/updating_pkgs.html#) earlier, but it was an overwhelming amount of information and I couldn't work out what was relevant to me.

**Comment by jakirkham** [comment]
Gotcha. How could we make it better to sift through? Smaller pages? Finer grained TOC? Something else?

**Comment by GenevieveBuckley** [comment]
> Gotcha. How could we make it better to sift through? Smaller pages? Finer grained TOC? Something else?

There's no high-level overview of what the overall process is, so I had no structure to fit any of that information into. That's the biggest thing that would help. There's no clear story for "this is how you move through a conda-forge process".

It was also hard to work out what was relevant to me, as a new maintainer to a project that already had a conda-forge feedstock set up. A lot of the getting started as a maintainer docs are about setting up a feedstock from scratch, which is great but not what I needed. I didn't want to spend ages reading through everything, I wanted to finish making the release!

It turns out that you don't actually need to know/understand very much to release new versions if the feedstock is already set up. But it would be much better if I *did* understand it better, because even the checklist of stuff that the conda-forge bot gives you to do before merging the PR is difficult to if you've never done it before. Even now I think I still get warnings and just ...ignore them, because I don't know how to fix it & the release was ok last time.

I also didn't have a good sense of what actions are handled automatically when PRs are merged here (eg: the new release is made available on conda-forge, a new person is automatically added to the maintainer team here). I think these are all symptoms of not understanding the overall process involved.

I understood packaging with pip before this but had zero clue about how conda packaging worked. I once asked in a tutorial, and was told "that's too complicated". I can see why they said that now :)

**Comment by jakirkham** [comment]
Great, thank you for writing that up 😄

Have filed an issue very briefly summarizing the need with a link to this comment for more details

**Comment by m-albert** [comment]
Thanks for adding me and documenting things in this PR, which might be useful in the future!

**Pull request merged**
